// Fleet coverage: who runs coding agents, and is synty watching them. This
// module owns agent-attribution detection over GitHub docs (Co-authored-by
// trailers, Generated-with footers, bot author logins) — the high-precision
// evidence that agents ran for a piece of work even when no tracker saw it.

/// Agent needles recognized inside an attribution line, mapped to the
/// canonical label reported on the doc. Matching is line-anchored (see
/// `detect_agent`): a prose mention of "claude" or "cursor" never counts.
const AGENT_MARKS: &[(&str, &str)] = &[
    ("claude", "claude"),
    ("copilot", "copilot"),
    ("cursor", "cursor"),
    ("devin", "devin"),
    ("codex", "codex"),
    ("aider", "aider"),
    ("openhands", "openhands"),
    ("windsurf", "windsurf"),
    ("gemini", "gemini"),
];

/// Author logins that ARE agents (lowercased, `[bot]` suffix and `app/`
/// prefix stripped before comparing). Exact matches only — CI bots like
/// dependabot or github-actions must not attribute.
const BOT_AUTHORS: &[(&str, &str)] = &[
    ("devin-ai-integration", "devin"),
    ("copilot-swe-agent", "copilot"),
    ("copilot", "copilot"),
    ("cursor", "cursor"),
    ("codegen-sh", "codegen"),
    ("sweep-ai", "sweep"),
];

/// The agent a GitHub PR/issue attributes its work to, if any: the author
/// itself is an agent account, or the body carries a Co-authored-by trailer /
/// "Generated with|by" footer naming one. Returns the canonical label.
pub fn detect_agent(text: &str, author: &str) -> Option<&'static str> {
    let norm = author.trim().to_lowercase();
    let norm = norm.strip_suffix("[bot]").unwrap_or(&norm);
    let norm = norm.strip_prefix("app/").unwrap_or(norm);
    for (login, label) in BOT_AUTHORS {
        if norm == *login {
            return Some(label);
        }
    }
    for line in text.lines() {
        let l = line.trim().to_lowercase();
        let attributing = l.starts_with("co-authored-by:")
            || l.contains("generated with")
            || l.contains("generated by");
        if !attributing {
            continue;
        }
        for (needle, label) in AGENT_MARKS {
            if l.contains(needle) {
                return Some(label);
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    // The standard trailer agents append to commits/PRs names the agent.
    #[test]
    fn coauthored_by_trailer_attributes_the_agent() {
        let body = "Fix the race in the tailer\n\nCo-authored-by: Claude <noreply@anthropic.com>";
        assert_eq!(detect_agent(body, "alice"), Some("claude"));
        assert_eq!(detect_agent("x\nCo-Authored-By: GitHub Copilot <copilot@github.com>", "bob"), Some("copilot"));
        assert_eq!(detect_agent("x\nco-authored-by: Cursor Agent", "bob"), Some("cursor"));
        assert_eq!(detect_agent("x\nCo-authored-by: Devin AI <devin@cognition.ai>", "bob"), Some("devin"));
    }

    // PR-body footers ("🤖 Generated with [Claude Code](…)", "Generated by
    // Copilot") attribute the same way.
    #[test]
    fn generated_with_footer_attributes_the_agent() {
        let body = "Add roster tests\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)";
        assert_eq!(detect_agent(body, "alice"), Some("claude"));
        assert_eq!(detect_agent("Summary of changes\n\nGenerated by Copilot", "alice"), Some("copilot"));
    }

    // A PR opened BY an agent account attributes regardless of body text.
    #[test]
    fn bot_author_login_attributes_the_agent() {
        assert_eq!(detect_agent("routine dependency bump", "devin-ai-integration[bot]"), Some("devin"));
        assert_eq!(detect_agent("routine change", "Copilot"), Some("copilot"));
        assert_eq!(detect_agent("routine change", "app/cursor"), Some("cursor"));
    }

    // Precision first: prose mentions of agent names and ordinary CI bots are
    // not attribution.
    #[test]
    fn prose_mentions_and_ci_bots_do_not_attribute() {
        assert_eq!(detect_agent("we should test claude here before shipping", "alice"), None);
        assert_eq!(detect_agent("the cursor jumps when scrolling the table", "alice"), None);
        assert_eq!(detect_agent("bump serde to 1.0.200", "dependabot[bot]"), None);
        assert_eq!(detect_agent("nightly corpus refresh", "github-actions[bot]"), None);
    }
}
